### ISSUE TITLE
Questions about generating .yml or .fea files from a new dataset

### ISSUE THREAD

**Issue by zizichong** [guohaoxiang/NH-Rep#1]
Hello, I am trying to use your project to process my dataset. I noticed that in addition to .obj files, corresponding .yml or .fea files are also needed when generating training data. However, my dataset only contains .obj files.

I would like to ask if it is possible to generate .yml or .fea files from .obj files? If so, could you provide some guidance or example code? Thank you very much!

**Comment by guohaoxiang** [comment]
Oh, I forget to mention about it. The fea file is just the same as my previous work CE-PolyCube:
https://github.com/msraig/CE-PolyCube#data-preparation
The feature file (*.fea) starts with the number of feature segments n, followed by n lines, where each line contains the two vertex indices of a feature edge segment.

**Comment by guohaoxiang** [comment]
And please follow the instructions in this part:
![image](https://github.com/guohaoxiang/NH-Rep/assets/29721619/8b343063-a181-4257-aa8b-7df3174bd711)
